name: Auto Assign to pView App

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign:
    runs-on: ubuntu-latest
    name: pView App project
    steps:
    - name: Assign issues to app project
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/ProfessorShep/bugs/projects/1'
